new_blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'posts.views.not_found'

posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    #  url(r'^detail/(?P<id>\d+)/$', post_detail), aşağısı belki tam slug için?
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

posts/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.FileField(null=True, blank=True)
    content = models.TextField()
    content_desc = models.TextField()
    category = models.CharField(max_length=60)
    meta_desc = models.CharField(max_length=150)
    keywords = models.CharField(max_length=120)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug

    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s" % (slug)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "slug",
            "content_desc",
            "content",
            "meta_desc",
            "category",
            "keywords",
            "image",
        ]
        widgets = {
          'content_desc': forms.Textarea(attrs={'rows': 2, 'cols': 120, 'data-provide': 'markdown'}),
          'content': forms.Textarea(attrs={'rows': 20, 'cols': 120, 'data-provide': 'markdown'}),
          'title': forms.TextInput(attrs={'autocomplete': 'off', 'class': 'form-control'}),
          'slug': forms.TextInput(attrs={'autocomplete': 'off', 'class': 'form-control'}),
          'meta_desc': forms.Textarea(attrs={'rows': 2, 'cols': 55, 'placeholder': 'Max 150 Character for Google Meta'}),
          'category': forms.TextInput(attrs={'autocomplete': 'off', 'class': 'form-control'}),
          'keywords': forms.TextInput(attrs={'autocomplete': 'off', 'class': 'form-control'}),
        }

posts/views.py
from urllib.parse import quote_plus as qp
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from .forms import PostForm
from .models import Post


def post_create(request):
    #  if not request.user.is_staff or not request.user.is_superuser:
    #    raise Http404
    if request.user.is_authenticated():
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            messages.success(request, "Successfully Created :)")
            return HttpResponseRedirect(instance.get_absolute_url())
    else:
        raise Http404
    context = {
        "form": form,
    }

    return render(request, "post_form.html", context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    context = {
        "title": instance.title,
        "instance": instance,
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    queryset_list = Post.objects.all()
    srch = request.GET.get("s")
    if srch:
        queryset_list = queryset_list.filter(
            Q(title__icontains=srch) |
            Q(content__icontains=srch) |
            Q(content_desc__icontains=srch) |
            Q(category__icontains=srch) |
            Q(keywords__icontains=srch) |
            Q(user__first_name__icontains=srch) |
            Q(user__last_name__icontains=srch)
        ).distinct()

    paginator = Paginator(queryset_list, 5)
    page = request.GET.get('p')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "<a href='/'>Ali GÖREN</a>"
    }

    return render(request, "post_list.html", context)


def post_update(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated():
        form = PostForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            messages.success(request, "Item Saved :)", extra_tags="html_safe")
            return HttpResponseRedirect(instance.get_absolute_url())
    else:
        raise Http404
    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated():
        instance.delete()
        messages.success(request, "Successfully Deleted :)")
        return redirect("posts:list")
    else:
        raise Http404

def not_found(request):
    return render(request,'404.html')

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="{{ instance.meta_desc }}">
        <meta name="keywords" content="{{ instance.keywords }}" >
        <title>{% block head_title %}Ali GÖREN{% endblock head_title %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <link rel="stylesheet" href='{% static "css/base.css" %}' media="screen" title="no title" charset="utf-8">
        <link rel="stylesheet" href='{% static "css/synt/zenburn.css" %}' media="screen" title="no title" charset="utf-8">
        <link rel="stylesheet" href='{% static "markdown/bootstrap_markdown.css" %}' media="screen" title="no title" charset="utf-8">
        <style media="screen">
            {% block style %}

            {% endblock style %}
        </style>
    </head>
    <body>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Anasayfa</a></li>
              {% if user.is_authenticated %}
                  {% if not request.path == "/" %}
                    {% if not request.path == "/create/" and not '/edit/' in request.path %}
                      <li><a href="{{ request.build_absolute_uri }}edit">Düzenle</a></li>
                      <li><a href="{{ request.build_absolute_uri }}delete">Sil</a></li>
                      <li><a href="/admin" target="_blank">Admin</a></li>
                    {% else %}
                       <li><a href="/admin" target="_blank">Admin</a></li>
                    {% endif %}
                  {% else %}
                      <li><a href="{{ request.build_absolute_uri }}create">Yeni Yazı</a>
                      </li><li><a href="/admin" target="_blank">Admin</a></li>
                  {% endif %}
              {% endif %}
            </ul>
          </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script id="dsq-count-scr" src="//aligren.disqus.com/count.js" async></script>
        <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
        <script type="text/javascript" src='{% static "markdown/bootstrap-markdown.js" %}'></script>
        <script type="text/javascript" src='{% static "markdown/bootstrap-markdown.tr.js" %}'></script>
        <script type="text/javascript" src='{% static "markdown/bootstrap.min.js" %}'></script>
        <script type="text/javascript" src='{% static "markdown/markdown.js" %}'></script>
        <script type="text/javascript" src='{% static "markdown/to-markdown.js" %}'></script>
        <script src='{% static "js/high_line_num.js" %}' charset="utf-8"></script>
        <script src='{% static "js/highlight.pack.js" %}' charset="utf-8"></script>
        <script>hljs.initHighlightingOnLoad();</script>
        <script>hljs.initLineNumbersOnLoad();</script>
    </body>
</html>

templates/error_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block head_title %}Ali GÖREN{% endblock head_title %}</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

        <link rel="stylesheet" href='{% static "css/base.css" %}' media="screen" title="no title" charset="utf-8">
        <style media="screen">
            {% block style %}

            {% endblock style %}
        </style>
    </head>
    <body>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/">Anasayfa</a></li>
            </ul>
          </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock content %}
        </div>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
        <script id="dsq-count-scr" src="//aligren.disqus.com/count.js" async></script>
    </body>
</html>

templates/messages_display.html
<!--
{% if messages %}
    <div class="messages">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
                {% endfor %}
            </ul>
    </div>
{%  endif %}
-->

templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load django_markdown %}
{% block head_title %}
    {{ instance.title }} | {{ block.super }}
{% endblock head_title %}


{% block content %}
<div class="col-md-24">
    <h1>{{ title }} <small>{{ instance.timestamp|timesince }} önce yayınlandı</small></h1>

    {% if instance.user.get_full_name %}
    <p><span class="label label-default">Author:</span> {{ instance.user.get_full_name }}</p>
    {% endif %}<h5><p><span class="label label-default">Kategori:</span> {{ instance.category }}</p></h5>
    <hr class="small">
    <div class="row">
        <div class="col-md-24">
            <div class="inde">
                <div class="caption">
                    {% if instance.image %}
                        <img src="{{ instance.image.url }}" class="img-responsive" />
                    {% endif %}
                    {% autoescape off %}
                    {{ instance.content_desc|markdown }}<br />
                    {{ instance.content|markdown }}
                    {% endautoescape %}
                    <br />
                    <h5><p><span class="label label-default">Etiketler:</span> {{ instance.keywords }}</p></h5>
                </div>
            </div>
        </div>
    </div>
</div>
<!--
<a class="btnz share twitter" href="https://twitter.com/intent/tweet?text={{ instance.content|truncatechars:80|urlify }}&url={{ request.build_absolute_uri }}&via=yazilimci_adam" target="_blank"><i class="fa fa-twitter"></i> Share on Twitter</a>
<a class="btnz share facebook" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank"><i class="fa fa-facebook"></i> Share on Facebook</a>
<a class="btnz share reddit" target="_blank" href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}share_string&title={{ instance.content|truncatechars:20|urlify }}">Share on Reddit</a>
<a class="btnz share gplus" href='https://plus.google.com/share?url={{ request.build_absolute_uri }}' target="_blank"><i class="fa fa-google-plus"></i> Share on Google Plus</a>
<a class="btnz share linkedin" target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.content|truncatechars:20|urlify }}&summary={{ instance.content|truncatechars:20|urlify }}&source={{ request.build_absolute_uri }}"><i class="fa fa-linkedin"></i> Share on LinkedIn</a>
-->
<hr class="small">
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//aligren.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% block content %}
<script language="JavaScript">
slugify = function(text) {
    var trMap = {
        'çÇ':'c',
        'ğĞ':'g',
        'şŞ':'s',
        'üÜ':'u',
        'ıİ':'i',
        'öÖ':'o',
        ' ':'-'
    };
    for(var key in trMap) {
        text = text.replace(new RegExp('['+key+']','g'), trMap[key]);
    }
    return  text.replace(/[^-a-zA-Z0-9\s]+/ig, '') // remove non-alphanumeric chars
                .replace(/\s/gi, "-") // convert spaces to dashes
                .replace(/[-]+/gi, "-") // trim repeated dashes
                .toLowerCase();

}
function GetTitleValue () {
    var title = document.getElementById ("id_title");
    return (title.value);
}
function SetSlugValue () {
    var slug = document.getElementById ("id_slug");
    slug.value = slugify(GetTitleValue());
}
</script>

<div class="col-md-12">
    <div class="row">

    <h1>Form!</h1>
    <form method="POST" action="" enctype="multipart/form-data" role="form">
        <div class="container">
            <div class="container-fluid">
                <div class="row">
                    <div class="panel panel panel-primary">
                        <div class="panel-heading">İçerik Ayarları</div>
                        <div class="panel-body">
                            <div class="form-group">
                                {% csrf_token %}
                                <label for="id_title">Title</label>
                                <p>{{ form.title }}</p>
                            </div>
                            <div class="form-group">
                                <label for="id_slug"><a onclick="SetSlugValue();" role="button">Slug URL!</a></label>
                                <p>{{ form.slug }}</p>
                            </div>
                            <div class="form-group">
                                <label for="id_category">Category!</label>
                                <p>{{ form.category }}</p>
                            </div>
                            <div class="form-group">
                                <label for="id_keywords">Keywords!</label>
                                <p>{{ form.keywords }}</p>
                            </div>
                            <div class="form-group">
                                {{ form.image }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6 pull-left">
                        <div class="panel panel panel-default">
                            <div class="panel-heading">Meta Açıklaması</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="id_meta_desc">Meta Description!</label>
                                    <p>{{ form.meta_desc }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 pull-left">
                        <div class="panel panel panel-success">
                            <div class="panel-heading">Özet Açıklaması</div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="id_content_desc">Content Description!</label>
                                    <p>{{ form.content_desc }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="panel panel panel-info">
                        <div class="panel-heading">İçerik</div>
                        <div class="panel-body">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label for="id_content">Content!</label>
                                    <p>{{ form.content }}</p>
                                </div>
                                <input type="submit" class="btn btn-default" value="Create Post!">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock content %}

templates/post_list.html
{% extends "base.html" %}
{% load django_markdown %}
{% block content %}
    <div class="col-md-12">
        <h1>{{ title|safe }}</h1>
        <form action="{% if not request.path == "/" %}/{% endif %}" method="GET">
            <div class="form-group">
                <p>
                    <input name="s" autocomplete="off" type="text" value="{{ request.GET.s}}" placeholder="Aramaya İnanıyorum..." />
                    <input type="submit" class="btn btn-default" value="Arama Şeyi">
                </p>
            </div>
        </form>
        {% if object_list|length %}
            {% for obj in object_list %}

                <div class="row">
                    <div class="col-md-24">
                        <div class="thumbnail">
                            <div class="caption">
                                <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.timestamp|timesince }} önce yayınlandı</small></h3>
                                {% if obj.user.get_full_name %}
                                    <p><span class="label label-default">Author: {{ obj.user.get_full_name }}</span> -
                                        {{ obj.category }} Kategorisinde yayınlandı - <a href='{{ obj.get_absolute_url }}#disqus_thread'>Yorumlar</a></p>
                                {% endif %}
                                <hr class="small">
                                <p>{{ obj.content_desc|markdown|truncatechars:200 }}</p>
                                <p><a class="btn btn-primary" href='{{ obj.get_absolute_url }}' role="button">Devamını Oku</a></p>
                            </div>
                        </div>
                    </div>
                    <hr>
                </div>
            {% endfor %}
            <ul class="pagination">
                {% if object_list.has_previous %}
                    <li><a href="?p={{ object_list.previous_page_number }}{% if request.GET.q %}&s={{ request.GET.q }}{% endif %}">Önceki</a></li>
                {% endif %}

                {% if object_list.number > 1 %}
                <li class="active">
                    <li><a href="?p={{ object_list.number }}">{{ object_list.number }}</a></li>
                </li>
                {% endif %}

                {% if object_list.has_next %}
                    <li><a href="?p={{ object_list.next_page_number }}{% if request.GET.s %}&s={{ request.GET.s }}{% endif %}">Sonraki</a></li>
                {% endif %}
            </ul>
        </div>
    {% else %}
    <div class="alert alert-warning">
      {% if request.GET.s %}
      <strong>Oop!</strong> "{{ request.GET.s }}" was not found!
      {% else %}
      <strong>Oop!</strong> No Post!
      {% endif %}
    </div>
    {% endif %}
{% endblock content %}